trap-commit

diff --git a/libs/grab_lib b/libs/grab_lib
--- a/libs/grab_lib
+++ b/libs/grab_lib
@@ -20,6 +20,7 @@ alias _rsync="rsync -rtxX -e 'ssh -q -T -c aes128-ctr -o Compression=no -x'"
 
 _foo=$(basename "$0")
 _fuu=$(basename "${BASH_SOURCE[0]}")
+_tgt="/etc/bind/zones-rpz"
 _red="\e[91m"
 _grn="\e[92m"
 _ylw="\e[93m"
@@ -30,6 +31,8 @@ _err="${_red}[FAIL]${_ncl}"
 _wrn="${_grn}WARNING:${_ncl}"
 _tks="${_red}TASKs${_ncl}"
 _cnt="${_cyn}CONTINUED to :${_ncl}"
+_shd="${_grn}'shutdown -c'${_ncl}"
+_rnr="{_cyn}rndc reload${_ncl}"
 
 readonly CONFIG="grab_cnf"
 test -r "${CONFIG}" || chmod 644 "${CONFIG}"
@@ -49,9 +52,9 @@ f_tmp() {   # remove temporary files, directories && arrays defined during the e
    find . -type d ! -name "." -print0 | xargs -0 -r rm -rf
    find /tmp -maxdepth 1 -type f -name "txt.adult" -print0 | xargs -r0 mv -t .
    }
-
 f_uset() { unset -v ar_{cat,CAT,db,dbc,DBC,dom,dmn,miss,reg,rpz,RPZ,sho,split,tmp,txt,url,zon} isDOWN; }
-f_trap() { printf "\n"; f_tmp; f_uset; exit 255; }
+f_klin() { printf "\n"; f_tmp; f_uset; }
+f_trap() { trap f_klin EXIT TERM; trap 'f_klin; exit 255' INT; }
 
 f_xcd() {   # exit code {7..20}
    for EC in $1; do
@@ -97,38 +100,40 @@ f_sm0() {   # display messages when getting options
    printf "ENTER: ${_cyn}[1|2|3|4|*]${_ncl}\t\t%s" ""
    }
 
-f_sm1() {   # display messages when 1'st option choosen
-   printf "\n${_red}[%s'st] TASK options choosen${_ncl}\n" "$RETVAL"
+f_sm1() {   # display messages when 1'st option chosen
+   printf "\n${_red}[%s'st] TASK options chosen${_ncl}\n" "$RETVAL"
    printf "${_cnt} ~eliminating duplicate entries between CATEGORY%s\n" ""
    printf "${_cyn}Performing tasks based on %s'st options ...${_ncl}\n" "$RETVAL"
    }
 
-f_sm2() {   # display messages when 2'nd option choosen
+f_sm2() {   # display messages when 2'nd option chosen
    f_sm5
    printf "${_cyn}Performing tasks based on %s'th options ...${_ncl}\n" "$RETVAL"
    }
 
-f_sm3() {   # display messages when 3'th option choosen
+f_sm3() {   # display messages when 3'th option chosen
    f_sm5
    printf "%28s serial at zone-files [rpz.*]\n" "~incrementing"
    printf "${_cyn}Performing tasks based on %s'th options ...${_ncl}\n" "$RETVAL"
    }
 
-f_sm4() {   # display messages when 4'th option choosen
+f_sm4() {   # display messages when 4'th option chosen
    f_sm5
    printf "%28s serial zone-files [rpz.*]\n" "~incrementing"
    printf "%28s latest [rpz.* and db.*] files to %s\n" "~syncronizing" "$HOST"
 
    if [[ $RNDC_RELOAD =~ [nN][oO] ]]; then
        printf "%6s${_wrn} host %s will REBOOT due to low memory\n" " " "$HOST"
-       printf "%18s ${_grn}'shutdown -c'${_ncl} at HOST: %s to abort" "use" "$HOST"
+       printf "%18s ${_shd} at HOST: %s to abort" "use" "$HOST"
+   else
+       printf "execute ${_rnr} at BIND9-server:%s\n" "$HOST"
    fi
 
    printf "\n${_cyn}Performing tasks based on %s'th options ...${_ncl}\n" "$RETVAL"
    }
 
 f_sm5() {   # nested in f_sm2 to f_sm4
-   printf "\n${_red}[%s'th] TASK options choosen${_ncl}\n" "$RETVAL"
+   printf "\n${_red}[%s'th] TASK options chosen${_ncl}\n" "$RETVAL"
    printf "${_cnt} ~eliminating duplicate entries between CATEGORY%s\n" ""
    printf "%25s all CATEGORIES to RPZ format [db.* files]\n" "~rewriting"
    }
@@ -182,27 +187,26 @@ f_syn() {   # passwordless ssh for backUP oldDB and rsync newDB
       [[ ${ar_dbc[*]} == "${ar_DBC[*]}" ]] || f_xcd 19 "$miss_DBC"
       [[ ${ar_rpz[*]} == "${ar_RPZ[*]}" ]] || f_xcd 19 "$miss_RPZ"
 
-      local _remdir="/etc/bind/zones-rpz/"
       local _ts; _ts=$(date "+%Y-%m-%d");
       local _ID; _ID="/home/rpz-$_ts.tar.gz"
 
-      _ssh -o BatchMode=yes "$HOST" true  >> /dev/null 2>&1 || f_xcd 7 "$HOST"
-      _ssh root@"$HOST" [[ -d $_remdir ]] || f_xcd 18 "$_remdir" "$HOST"
+      f_ssh
       printf "\n${_inf} archiving current RPZ-dBase, save in %s:%s\n" "$HOST" "$_ID"
       _ssh root@"$HOST" "cd /etc/bind; tar -I pigz -cf $_ID zones-rpz"
       printf "${_inf} find and remove old RPZ-dBase archive in %s:/home\n" "$HOST"
       _ssh root@"$HOST" "find /home -regextype posix-extended -regex '^.*(tar.gz)$' -mmin +1430 -print0 | xargs -0 -r rm"
-      printf "${_inf} syncronizing the latest RPZ-dBase to %s:%s\n" "$HOST" "$_remdir"
-      _rsync {rpz,db}.* root@"$HOST":"$_remdir"
+      printf "${_inf} syncronizing the latest RPZ-dBase to %s:%s\n" "$HOST" "$_tgt"
+      _rsync {rpz,db}.* root@"$HOST":"$_tgt"
 
       if [[ $RNDC_RELOAD =~ [yY][eE][sS] ]]; then
-         printf "Reload BIND9-server:%s\n" "$HOST"
+         # sufficient RAM is required by $HOST"
+         printf "execute ${_rnr} at BIND9-server:%s\n" "$HOST"
          _ssh root@"$HOST" "rndc reload"
       else
          # $HOST" will reboot [after +@ minute] due to low memory
          printf "${_inf} host: ${_grn}%s${_ncl} scheduled for reboot at %s\n" "$HOST" "$(faketime -f "+5m" date +%H:%M:%S)"
          _ssh root@"$HOST" "shutdown -r 5 --no-wall >> /dev/null 2>&1"
-         printf "${_inf} use ${_grn}'shutdown -c'${_ncl} at host: %s to abort" "$HOST"
+         printf "${_inf} use ${_shd} at host: %s to abort" "$HOST"
       fi
    else
       f_xcd 16 "$HOST"
@@ -280,12 +284,9 @@ f_ip4() {   # used by grab_build.sh
 
 f_cer() {   # used by grab_cereal.sh to copy zone-files by passwordless ssh-scp
    if ping -w 1 "$HOST" >> /dev/null 2>&1; then
-      local _remdir="/etc/bind/zones-rpz"
-      _ssh -o BatchMode=yes "$HOST" /bin/true  >> /dev/null 2>&1 || f_xcd 7 "$HOST"
-      _ssh root@"$HOST" [[ -d $_remdir ]] || f_xcd 18 "$_remdir" "$HOST"
-
+      f_ssh
       for a in $1; do
-         if scp -qr root@"$HOST":"$_remdir"/"$a" "$_DIR"; then
+         if scp -qr root@"$HOST":"$_tgt"/"$a" "$_DIR"; then
             :      # do nothing
          else
             local origin="https://raw.githubusercontent.com/ngadmini/Grabbing-Blacklist-for-Bind9-RPZ/master/zones-rpz/"
@@ -295,7 +296,7 @@ f_cer() {   # used by grab_cereal.sh to copy zone-files by passwordless ssh-scp
             printf "${_inf} successfully get %s from origin:\n%s%s\n" "$a" "$origin" "$a"
          fi
       done
-      printf "\n${_inf} retrying TASK again%s" ""
+      printf "\n${_inf} retry to running TASK again%s" ""
       exec "$0"
    else
       f_xcd 16 "$HOST"
@@ -304,8 +305,8 @@ f_cer() {   # used by grab_cereal.sh to copy zone-files by passwordless ssh-scp
 
 f_rvu() {   # used by grab_http.sh
    tools="grab_dedup.sh, grab_build.sh, grab_cereal.sh and grab_scp.sh"
-   printf "Nothing choosen, just stop right now\n"
-   printf "You can still run:\n${_red}%s${_ncl}\nanytime after this\n" "$tools"
+   printf "\nnothing chosen, just stop right now\n"
+   printf "you can still execute scripts below, anytime after this\n${_red}%s${_ncl}\n" "$tools"
    }
 
 f_sed() { _sed "s/ /\n/g" | sort | uniq -u | tr "\n" " "; }
@@ -313,3 +314,8 @@ f_pms() { find . -regextype posix-extended -regex "^.*(db|rpz).*" -not -perm 640
 f_fnd() { find . -maxdepth 1 -type f -name "$1" | _sed -e "s/\.\///" | sort; }
 f_frm() { find . -maxdepth 1 -type f -name "$1" -print0 | xargs -0 -r rm; }
 f_cat() { find . -maxdepth 1 -type d | _sed -e "1d;s/\.\///" | sort; }
+
+f_ssh() { # nested in f_syn and f_cer
+   _ssh -o BatchMode=yes "$HOST" true  >> /dev/null 2>&1 || f_xcd 7 "$HOST"
+   _ssh root@"$HOST" [[ -d $_tgt ]] || f_xcd 18 "$_tgt" "$HOST"
+   }
