v6.8.commit

diff --git a/libs/grab_library b/libs/grab_library
--- a/libs/grab_library
+++ b/libs/grab_library
@@ -1,42 +1,39 @@
 # TAGS
 #   grab_library
-#   v6.7
+#   v6.8
 # AUTHOR
 #   ngadimin@warnet-ersa.net
-# NOTE
+# TL;DR
+#   don't change unless you know what you're doing
 #   intended for use by other scripts, not to be executed directly.
-# shellcheck disable=SC2034 disable=SC2148 disable=SC2154
+#   see README and LICENSE
+# shellcheck disable=SC2034 disable=SC2148 disable=SC2154 disable=SC2059
 
 shopt -s expand_aliases
-alias _sort="LC_ALL=C sort --buffer-size=80% --parallel=3"
-alias _sed="LC_ALL=C sed"
 alias _grep="LC_ALL=C grep"
-alias _ssh="ssh -q -T -c aes128-ctr -o Compression=no -x"
 alias _rsync="rsync -rtxX -e 'ssh -q -T -c aes128-ctr -o Compression=no -x'"
+alias _sed="LC_ALL=C sed"
+alias _sort="LC_ALL=C sort --buffer-size=80% --parallel=3"
+alias _ssh="ssh -q -T -c aes128-ctr -o Compression=no -x"
 
-_foo="${0##*/}"
-_ver=$(grep -P "^#\s{2,}v.*" "${_foo}" | cut -d' ' -f4)
 _fkt=$(faketime -f "+5m" date +%H:%M:%S)
+_foo="${0##*/}"
 _prl='^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])$'
-printf -v _lct "%s %s" "$(date +%Y%m%d_%T)" "$(date | awk -F' ' '{print $6}')"
+_ver=$(grep -P "^#\s{2,}v.*" "${_foo}" | cut -d' ' -f4)
 origin="https://raw.githubusercontent.com/ngadmini/Grabbing-Blacklist-for-Bind9-RPZ/${_ver}"
+printf -v _lct "%s %s" "$(date +%Y%m%d_%T)" "$(date | awk -F' ' '{print $6}')"
 
 # colorizing
-_red='\e[91m'
-_grn='\e[92m'
-_ylw='\e[93m'
-_cyn='\e[96m'
-_ncl='\e[0m'
+_cyn='\e[96m'; _grn='\e[92m'; _ncl='\e[0m'; _red='\e[91m'; _ylw='\e[93m'
+_err="${_red}[FAIL]${_ncl}"; _hnt="${_cyn}[HINT]${_ncl}"; _inf="${_ylw}[INFO]${_ncl}"
+_CYN="${_cyn}%s${_ncl}"; _GRN="${_grn}%s${_ncl}"; _RED="${_red}%s${_ncl}"; _YLW="${_ylw}%s${_ncl}"
 _ccl="${_grn}'Ctrl C'${_ncl}"
 _cnt="${_cyn}CONTINUED to :${_ncl}"
-_err="${_red}[FAIL]${_ncl}"
-_inf="${_ylw}[INFO]${_ncl}"
-_rnr="${_cyn}'rndc reload'${_ncl}"
+_pre="${_ylw}PREPARING TASKs:${_ncl}"
+_rnr="${_grn}'rndc reload'${_ncl}"
 _shd="${_grn}'shutdown -c'${_ncl}"
 _tks="${_red}TASKs${_ncl}"
 _wrn="${_grn}WARNING:${_ncl}"
-_pre="${_ylw}PREPARING TASKs:${_ncl}"
-_hnt="${_cyn}[HINT]${_ncl}"
 
 f_tmp() {   # remove temporary files, directories & arrays, generated during script execution
    find . -regex "^.*\(sed\|dmn\|tmr\|tm[pq]\|txt.adulta\).*\|.*gz$" -print0 | xargs -0 -r rm -rf
@@ -46,7 +43,7 @@ f_tmp() {   # remove temporary files, directories & arrays, generated during scr
 f_klin() { printf "\n"; f_tmp; f_uset; }
 f_trap() { trap f_klin EXIT TERM; trap 'f_klin; exit 255' INT; }
 f_uset() {
-   unset -v ar_{cat,CAT,cnf,CNF,db,dbc,DBC,dom,dmn,miss,reg,rpz,RPZ,sh,sho,split,tmp,txt,url,VAR,zh,zon} isDOWN index
+   unset -v ar_{cat,CAT,cnf,CNF,dbc,DBC,dom,dmn,miss,reg,rpz,RPZ,sh,sho,split,tmp,txt,url,VAR,zh,zon} isDOWN index
 }
 
 f_xcd() {   # exit code {7..19}
@@ -59,24 +56,24 @@ f_xcd() {   # exit code {7..19}
          10) printf "\n%s\n%s\n" "${_xcd}" "you must execute as non-root privileges"; return 1;;
          11) _msj="urls. it should consist of ${index[ar_url]} urls"
              printf -v _lmm "%s" "$(basename "$2"): $(wc -l < "$2")"
-             printf "\n%s\n%s %s\n" "${_xcd}" "${_lmm}" "${_msj}"; return 1;;
+             printf "\n%s\n%s\n" "${_xcd}" "${_lmm} ${_msj}"; return 1;;
          12) _msg="lines. it should consist of ${index[ar_reg]} lines"
              printf -v _lnn "%s" "$(basename "$2"): $(wc -l < "$2")"
-             printf "\n%s\n%s %s\n" "${_xcd}" "${_lnn}" "${_msg}"; return 1;;
+             printf "\n%s\n%s\n" "${_xcd}" "${_lnn} ${_msg}"; return 1;;
          13) _re0='[Exit Codes section] https://curl.se/docs/manpage.html'
              _re1='[Status Codes section] https://en.wikipedia.org/wiki/List_of_HTTP_status_codes'
              _unk='check if there is a typo in grab_urls. if spelling is correct, please see'
              printf "${_err} %s:\n%s\n%s\n" "${_unk}" "${_re0}" "${_re1}"; exit 1;;
          14) printf "\n%s\n%s\n" "${_xcd}" "download failed from origin"; return 1;;
-         15) printf -v _ind "${_cyn}%s${_ncl}" "$(echo "${index[*]}" | grep "[\.,]")"
+         15) printf -v _ind "${_CYN}" "$(echo "${index[*]}" | grep "[\.,]")"
              printf "%s\ninvalid index's values: %s\n" "${_xcd}" "${_ind}"
              printf "${_hnt} use numeric in index's values%s\n"; return 1;;
-         16) printf -v _lin "%s" "$(grep -En "^(HOST|#HOST)" "$CNF" | cut -d: -f1)"
+         16) printf -v _lin "%s" "$(grep -En "^(HOST|#HOST)" "${CNF}" | cut -d: -f1)"
              _ext=$(printf "${_err} ${CNF##*/} : at line ${_lin}. exit code: %s" "${EC}")
              printf "%s\n%s : if spelling is correct, maybe isDOWN\n" "${_ext}" "${HOST}"; return 1;;
-         17) printf "\n${_inf} misMATCH file(s): ${_cyn}%s${_ncl}\n%s\n" "$2" "${_xcd}"; return 1;;
-         18) printf "\n%s: ${_cyn}%s${_ncl} doesn't exis\n" "${_xcd}" "$(basename "$2")"; return 1;;
-         19) printf "\n%s: required file(s):\n${_cyn}%s${_ncl}\n" "${_xcd}" "$2"; return 1;;
+         17) printf "\n${_inf} misMATCH file(s): ${_CYN}\n%s\n" "$2" "${_xcd}"; return 1;;
+         18) printf "\n%s: ${_CYN} doesn't exis\n" "${_xcd}" "$(basename "$2")"; return 1;;
+         19) printf "\n%s: required file(s):\n${_CYN}\n" "${_xcd}" "$2"; return 1;;
           *) _ukn="Unknown exit code [f_xcd $1], please check:"
              printf -v _knw "%s" "${_foo} at line $(grep -n "f_xcd $1" "${_foo}" | cut -d: -f1)"
              printf "\n${_err} %s\n%s\n" "${_ukn}" "${_knw}"; return 1;;
@@ -85,24 +82,24 @@ f_xcd() {   # exit code {7..19}
 }
 
 f_sm0() {   # display messages when getting options
-   printf "${_cyn}CHOOSE one of the following options :${_ncl}%s\n"
+   printf "${_CYN}\n" "CHOOSE one of the following options :"
    printf "%4s) eliminating duplicate entries between CATEGORY\n" "1"
    printf "%4s) option [1] and rewriting all CATEGORIES to RPZ format [db.* files]\n" "2"
-   printf "%4s) options [1,2] and incrementing serial at zone-files [rpz.*]\n" "3"
+   printf "%4s) options [1,2] and incrementing serial zone-files [rpz.*]\n" "3"
    printf "%4s) options [1,2,3] and syncronizing latest [rpz.* and db.*] files to %s\n" "4" "$1"
    if [[ ${RNDC_RELOAD} =~ [nN][oO] ]]; then
       printf "%6s${_wrn} host %s will REBOOT due to low memory\n" "" "${HOST}"
       printf "%18s ${_shd} at HOST: %s to abort\n" "use" "${HOST}"
    else
-      printf "%6salso, ${_rnr} will be executed too\n" ""
+      printf "%6s${_wrn} ${_rnr} will be executed too.\n" ""
    fi
-   printf "%4s) use ${_grn}Ctrl+C${_ncl} to quit\n" "^C"
-   printf "ENTER: ${_cyn}[1|2|3|4]${_ncl} or Ctrl+C to quit%s\n"
+   printf "%4s) use ${_ccl} to quit\n" "^C"
+   printf "ENTER: ${_CYN} or ${_ccl} to quit\n" "[1|2|3|4]"
 }
 
 f_sm1() {   # f_sm[1..4] = display messages when chosing option
    printf "\n${_red}[%s'st] TASK options chosen${_ncl}\n" "$RETVAL"
-   printf "${_cnt} 1) eliminating duplicate entries between CATEGORY%s\n"
+   printf "${_cnt} 1) eliminating duplicate entries between CATEGORY\n"
    f_sm12 "st"
 }
 
@@ -124,7 +121,7 @@ f_sm4() {
 
 f_sm5() {   # nested in f_sm[2..4]
    printf "\n${_red}[%s'%s] TASK options chosen${_ncl}\n" "$RETVAL" "$1"
-   printf "${_cnt} 1) eliminating duplicate entries between CATEGORY%s\n"
+   printf "${_cnt} 1) eliminating duplicate entries between CATEGORY\n"
    printf "%27s all CATEGORIES to RPZ format [db.* files]\n" "2) rewriting"
 }
 
@@ -136,17 +133,17 @@ f_sm6() {   # display FINISH messages
 
 # f_sm[7..12] = display processing messages
 f_sm7() { printf "%12s: %-64s\t" "grab_$1" "${2##htt*\/\/}"; }
-f_sm8() { printf "\nprocessing ${_cyn}%s CATEGORY${_ncl} with (%d) additional remote-files\n" "${1^^}" "$2"; }
+f_sm8() { printf "\nprocessing ${_CYN} with (%d) additional remote-files\n" "${1^^} CATEGORY" "$2"; }
 f_sm9() { printf "%12s: %-64s\t" "fixing" "bads, duplicates and false entries at ${1^^}"; }
-f_sm10() { printf "\n${_tks} based on %s'%s options: ${_grn}%sDONE${_ncl}\n" "$RETVAL" "$1"; }
-f_sm11() { printf "\n${_inf} completed ${_cyn}IN %s:%s${_ncl}\n" "$1" "$2"; }
+f_sm10() { printf "\n${_tks} based on %s'%s options: ${_GRN}\n" "$RETVAL" "$1" "DONE"; }
+f_sm11() { printf "\n${_inf} completed IN ${_CYN}\n" "$1:$2"; }
 f_sm12() { printf "${_cyn}Performing tasks based on %s'%s options ...${_ncl}\n" "$RETVAL" "$1"; }
-f_ok() { printf "${_grn}%s${_ncl}\n" "isOK"; }            # display isOK
-f_do() { printf "${_grn}%s${_ncl}\n" "DONE"; }            # display DONE
-f_no() { printf "${_red}%s notFOUND${_ncl}\n" "$1"; }     # display notFOUND
+f_ok() { printf "${_GRN}\n" "isOK"; }                      # display isOK
+f_do() { printf "${_GRN}\n" "DONE"; }                      # display DONE
+f_no() { printf "${_red}%s notFOUND${_ncl}\n" "$1"; }      # display notFOUND
 
 # grabbing raw-domains && fixing false and bad entry
-f_add() { curl -C - -fs "$1" || f_xcd 14 "$1"; }          # grabbing raw-domains
+f_add() { curl -C - -kfs "$1" || f_xcd 14 "$1"; }          # grabbing raw-domains
 f_fix() { f_sm9 "$1"; _sort -u "$2" | _sed -e "$3" -e "$4" > "$5"; f_do; }
 f_ip() {   # capture and throw ip-address entry to ipv4 CATEGORY. save it into sub-net
    _grep -P "${_prl}" "$1" | _sed -e "/\/[0-9]\{2\}$/ ! s/$/\/32/" >> "$2"
@@ -155,8 +152,7 @@ f_ip() {   # capture and throw ip-address entry to ipv4 CATEGORY. save it into s
 
 f_fip() {
    printf "%12s: %-64s\t" "moving" "IP-address entries into $3 CATEGORY"
-   f_ip "$@"
-   f_do
+   f_ip "$@"; f_do
    printf "%12s: %'d entries.\n" "acquired" "$(wc -l < "$1")"
 }
 
@@ -175,10 +171,7 @@ f_ssh() {   # nested in f_cer and needed by grab_rsync
 }
 
 f_crawl() {   # verify remote-urls isUP
-   set +e
-   ar_sho=()
-   isDOWN=()
-   local i=-1
+   set +e; ar_sho=(); isDOWN=(); local i=-1
    while IFS='' read -r line; do
       # slicing remote-urls && add as an element to ${ar_sho[@]}
       local lll; lll="${line##htt*\/\/}"
@@ -186,30 +179,28 @@ f_crawl() {   # verify remote-urls isUP
       local l; l="${lll/\/*/}"
       local p_url; p_url="$l/..?../$ll"
       local statusCode
-      statusCode=$(curl -C - -ks -o /dev/null -I -w "%{http_code}" "${line}"; echo " exit code: $?")
+      statusCode=$(curl -C - -kso /dev/null -I -w "%{http_code}" "${line}"; echo " exit code: $?")
       ((i++))
       ar_sho+=("${p_url}")
       printf "%12s: %-64s\t" "urls_${i}" "${ar_sho[i]}"
       if [[ $statusCode != 2* ]]; then
-         printf "${_red}%s${_ncl}\n" "$statusCode"
+         printf "${_RED}\n" "$statusCode"
          isDOWN+=("[status code:${statusCode}] ${line}")
       else
-         printf "${_grn}%s${_ncl}\n" "isUP"
+         printf "${_GRN}\n" "isUP"
       fi
    done < "$1"
 
    if [[ ${#isDOWN[@]} -eq 0 ]]; then
-      printf "%30s\n" " " | tr " " -
-      printf "%s\n" "All URLS of remote-files isUP."
+      printf "%30s\n" " " | tr " " -; printf "%s\n" "All URLS of remote-files isUP."
    else
-      printf "%84s\n" " " | tr " " -
-      printf "${_cyn}%s${_ncl}\n" "${isDOWN[@]}"
+      printf "%84s\n" " " | tr " " -; printf "${_CYN}\n" "${isDOWN[@]}"
       f_xcd 13
    fi
    set -u
 }
 
-f_dupl() { printf "eliminating duplicate entries based on ${_cyn}%s${_ncl}\n" "${1^^}"; }
+f_dupl() { printf "eliminating duplicate entries based on ${_CYN}\n" "${1^^}"; }
 f_ddup() {  # used by grab_duplic.sh
    printf "%11s = deduplicating %s entries \t\t" "STEP $6.$1" "$2"
    _sort "$3" "$4" | uniq -d | _sort -u > "$5"
@@ -248,13 +239,13 @@ f_cer() {   # used by grab_cereal.sh to copy zone-files with passwordless ssh & 
       if scp root@"${HOST}":"${ZONE_DIR}"/"${a}" "${_DIR}" >> /dev/null 2>&1; then
          printf "${_inf} successfully get %s from %s\n" "${a}" "${HOST}"
       else
-         printf "${_err} %s not found in %s. %s\n" "${a}" "${HOST}" "try to get from origin:"
+         printf "${_err} %s not found in %s\n" "${a}" "${HOST}. try to get from origin:"
          printf "%s\n" "${origin}/zones-rpz/${a}"
          curl -C - -fs "${origin}/zones-rpz/""${a}" >> "${a}" || f_xcd 14
          printf "${_inf} successfully get %s from origin\n" "${a}"
       fi
    done
-   printf "${_inf} retry to running TASK again%s\n"
+   printf "${_inf} retry to running TASK again\n"
    exec "$0"
 }
 
@@ -279,11 +270,11 @@ f_cnf() {   # variables in file configuration
    if [[ -e ${CNF} ]]; then
       [[ -r ${CNF} ]] || chmod 644 "${CNF}"
       ar_cnf=(HOST LC_NUMERIC RNDC_RELOAD RPZ_DOM RPZ_IPV ZONE_DIR)
-      mapfile -t ar_CNF < <(_grep -Ev "^(#|*$)" "${CNF}" | _sed -e "s/[ ^ ]=/=/g" | cut -d= -f1 | sort)
+      mapfile -t ar_CNF < <(_grep -E "^[A-Z]" "${CNF}" | _sed -e "s/[ ^ ]=/=/g" | cut -d= -f1 | sort)
       if [[ ${ar_CNF[*]} == "${ar_cnf[*]}" ]]; then
          # get values supplied by "${CNF}", instead of "source ${CNF}"
          _ptr="s/=[ ^ ]/=/g;s/CNAME\(\t\|\s.*\)\./CNAME ./g;s/['\"#]//g;s/\( \|\t\)\{2,\}.*//g;s/\. [a0-z9].*/\./g"
-         mapfile -t ar_VAR < <(_grep -Ev "^(#|*$)" "${CNF}" | _sed -e "${_ptr}"| sort | cut -d= -f2)
+         mapfile -t ar_VAR < <(_grep -E "^[A-Z]" "${CNF}" | _sed -e "${_ptr}"| sort | cut -d= -f2)
          for ARG in "${!ar_VAR[@]}"; do
             printf -v "${ar_CNF[ARG]}" "%s" "${ar_VAR[ARG]}"
          done
