update.commit

diff --git a/libs/grab_library b/libs/grab_library
--- a/libs/grab_library
+++ b/libs/grab_library
@@ -1,6 +1,6 @@
 # TAGS
 #   grab_library
-#   v7.7-alpha
+#   v6.6
 # AUTHOR
 #   ngadimin@warnet-ersa.net
 # NOTE
@@ -43,40 +43,41 @@ f_tmp() {   # remove temporary files, directories && arrays. generated during sc
    find . -type d ! -name "." -print0 | xargs -0 -r rm -rf
    find /tmp -maxdepth 1 -type f -name "txt.*" -print0 | xargs -r0 mv -t .
 }
-f_uset() { unset -v ar_{cat,CAT,cnf,CNF,db,dbc,DBC,dom,dmn,miss,reg,rpz,RPZ,sho,split,tmp,txt,url,VAR,zon} isDOWN; }
 f_klin() { printf "\n"; f_tmp; f_uset; }
-f_trap() { trap f_klin EXIT TERM; trap 'f_klin; exit 255' INT; }
+f_trap() { trap f_klin EXIT TERM; trap 'f_klin; printf "bye!\n"; exit 255' INT; }
+f_uset() { unset -v ar_{cat,CAT,cnf,CNF,db,dbc,DBC,dom,dmn,miss,reg,rpz,RPZ,sho,split,tmp,txt,url,VAR,zon} isDOWN index; }
 
-f_xcd() {   # exit code {7..20}
+f_xcd() {   # exit code {7..21}
    for EC in $1; do
-      local _xcd; _xcd=$(printf "${_err} $_foo: at line ${BASH_LINENO[0]}. exit code %s" "$EC")
-      local _xce; _xce=$(printf "${_err} $_fuu: at line ${BASH_LINENO[0]}. exit code %s" "$EC")
+      local _xcd; _xcd=$(printf "${_err} $_foo: at line ${BASH_LINENO[0]}. exit code %s" "${EC}")
+      local _xce; _xce=$(printf "${_err} $_fuu: at line ${BASH_LINENO[0]}. exit code %s" "${EC}")
       case $EC in
-          7) printf "\n%s\n%s\n" "$_xcd" "required passwordless ssh to remote host: '$2'"; return 1;;
-          8) printf "\n%s\n%s\n" "$_xcd" "required '$2' but it's not installed"; return 1;;
-          9) printf "\n%s\n%s\n" "$_xcd" "'$2' required '$3' but it's not installed"; return 1;;
-         10) printf "\n%s\n%s\n" "$_xcd" "you must execute as non-root privileges"; return 1;;
+          7) printf "\n%s\n%s\n" "${_xcd}" "required passwordless ssh to remote host: '$2'"; return 1;;
+          8) printf "\n%s\n%s\n" "${_xcd}" "required '$2' but it's not installed"; return 1;;
+          9) printf "\n%s\n%s\n" "${_xcd}" "'$2' required '$3' but it's not installed"; return 1;;
+         10) printf "\n%s\n%s\n" "${_xcd}" "you must execute as non-root privileges"; return 1;;
          11) _msj='urls. it should consist of 22 urls'
              printf -v _lmm "%s" "$(basename "$2"): $(wc -l < "$2")"
-             printf "\n%s\n%s %s\n" "$_xcd" "$_lmm" "$_msj"; return 1;;
+             printf "\n%s\n%s %s\n" "${_xcd}" "${_lmm}" "${_msj}"; return 1;;
          12) _msg='lines. it should consist of 3 lines'
              printf -v _lnn "%s" "$(basename "$2"): $(wc -l < "$2")"
-             printf "\n%s\n%s %s\n" "$_xcd" "$_lnn" "$_msg"; return 1;;
-         13) _ref='https://en.wikipedia.org/wiki/List_of_HTTP_status_codes'
-             _unk='Check out [grab_urls]. if those url[s] are correct, please reffer to'
-             printf "${_err} %s:\n%s\n" "$_unk" "$_ref"; exit;;
-         14) printf "\n%s\n%s\n" "$_xcd" "download failed from '$2'"; return 1;;
-         15) printf "\n%s\n%s\n" "$_xcd" "category: must equal 6"; return 1;;
+             printf "\n%s\n%s %s\n" "${_xcd}" "${_lnn}" "${_msg}"; return 1;;
+         13) _re0='[Exit Codes section] https://curl.se/docs/manpage.html'
+             _re1='[Status Codes section] https://en.wikipedia.org/wiki/List_of_HTTP_status_codes'
+             _unk='check out [grab_urls]. if url[s] are correct, please see'
+             printf "${_err} %s:\n%s\n%s\n" "${_unk}" "${_re0}" "${_re1}"; exit 1;;
+         14) printf "\n%s\n%s\n" "${_xcd}" "download failed from '$2'"; return 1;;
+         15) printf "\n%s\n%s\n" "${_xcd}" "category: must equal 6"; return 1;;
          16) printf -v _lin "%s" "$(grep -En "^(HOST|#HOST)" "$CNF" | cut -d: -f1)"
-             _ext=$(printf "${_err} ${CNF##*/} : at line $_lin. exit code: %s" "$EC")
-             printf "\n%s\n%s : if this address is correct, maybe isDOWN\n" "$_ext" "${HOST}"; return 1;;
-         17) printf "\n%s\nmissing file: %s\n" "$_xcd" "$(basename "$2")"; return 1;;
-         18) printf "\n%s\n%s\n" "$_xce" """$2"" doesn't exist in ""$3"""; return 1;;
-         19) printf "%s\n%s\n" "$_xcd" "MATCH file name: ""$2"""; return 1;;
-         20) printf "%s\nmissing file: %s\n" "$_xce" "$(basename "$2")"; return 1;;
+             _ext=$(printf "${_err} ${CNF##*/} : at line ${_lin}. exit code: %s" "${EC}")
+             printf "\n%s\n%s : if this address is correct, maybe isDOWN\n" "${_ext}" "${HOST}"; return 1;;
+         17) printf "\n%s\nmissing file: %s\n" "${_xcd}" "$(basename "$2")"; return 1;;
+         18) printf "\n%s\n%s\n" "${_xce}" """$2"" doesn't exist in ""$3"""; return 1;;
+         19) printf "%s\n%s\n" "${_xcd}" "MATCH file name: ""$2"""; return 1;;
+         20) printf "%s\nmissing file: %s\n" "${_xce}" "$(basename "$2")"; return 1;;
           *) _ukn="Unknown exit code [f_xcd $1], please check:"
              printf -v _knw "%s" "$_foo at line $(grep -n "f_xcd $1" "$_foo" | cut -d: -f1)"
-             printf "\n${_err} %s\n%s\n" "$_ukn" "$_knw"; return 1;;
+             printf "\n${_err} %s\n%s\n" "${_ukn}" "${_knw}"; return 1;;
       esac
    done
 }
@@ -85,7 +86,7 @@ f_sm0() {   # display messages when getting options
    printf "${_cyn}CHOOSE one of the following options :${_ncl}%s\n"
    printf "%4s) eliminating duplicate entries between CATEGORY\n" "1"
    printf "%4s) option [1] and rewriting all CATEGORIES to RPZ format [db.* files]\n" "2"
-   printf "4%s) options [1,2] and incrementing serial at zone-files [rpz.*]\n" "3"
+   printf "%4s) options [1,2] and incrementing serial at zone-files [rpz.*]\n" "3"
    printf "%4s) options [1,2,3] and syncronizing latest [rpz.* and db.*] files to %s\n" "4" "$1"
    if [[ ${RNDC_RELOAD} =~ [nN][oO] ]]; then
       printf "%6s${_wrn} host %s will REBOOT due to low memory\n" "" "${HOST}"
@@ -93,8 +94,8 @@ f_sm0() {   # display messages when getting options
    else
       printf "%6salso, ${_rnr} will be executed too\n" ""
    fi
-   printf "%4s) use Ctrl+c to quit\n" "c"
-   printf "ENTER: ${_cyn}[1|2|3|4]${_ncl} or Ctrl+c to quit%s\n"
+   printf "%4s) use Ctrl+C to quit\n" "*"
+   printf "ENTER: ${_cyn}[1|2|3|4]${_ncl} or Ctrl+C to quit%s\n"
 }
 
 f_sm1() {   # f_sm[1...4] = display messages when chosing option
@@ -226,13 +227,14 @@ f_crawl() {   # verify remote-urls isUP
       local ll; ll="$(basename "$line")"
       local l; l="${lll/\/*/}"
       local p_url; p_url="$l/..?../$ll"
-      local statusCode; statusCode=$(curl -C - -ks -o /dev/null -I -w "%{http_code}" "${line}")
+      local statusCode
+      statusCode=$(curl -C - -ks -o /dev/null -I -w "%{http_code}" "${line}"; echo " exit code: $?")
       ((i++))
       ar_sho+=("${p_url}")
       printf "%12s: %-64s\t" "urls_${i}" "${ar_sho[i]}"
       if [[ $statusCode != 2* ]]; then
-         printf "${_red}%s${_ncl}\n" "Code: $statusCode"
-         isDOWN+=("[Respon Code:${statusCode}] ${line}")
+         printf "${_red}%s${_ncl}\n" "$statusCode"
+         isDOWN+=("[status code:${statusCode}] ${line}")
       else
          printf "${_grn}%s${_ncl}\n" "isUP"
       fi
@@ -303,12 +305,6 @@ f_cer() {   # used by grab_cereal.sh to copy zone-files with passwordless ssh & 
    fi
 }
 
-f_rvu() {   # used by grab_http.sh
-   tools='grab_duplic.sh, grab_build.sh, grab_cereal.sh and grab_rsync.sh'
-   printf "\nnothing chosen, just stop right now\n"
-   printf "you can still execute scripts below, anytime after this\n${_red}%s${_ncl}\n" "$tools"
-}
-
 f_sed() { _sed "s/ /\n/g" | sort | uniq -u | tr "\n" " "; }
 f_pms() { find . -regex "^.*\(db\|rpz\).*" -not -perm 640 -exec chmod -R 640 {} \;; }
 f_fnd() { find . -type f -name "$1" | _sed -e "s/\.\///" | sort; }
@@ -333,7 +329,7 @@ f_cnf() {   # variables in file configuration
       mapfile -t ar_CNF < <(_grep -Ev "^(#|*$|\s|\t)" "${CNF}" | _sed -e "s/[ ^ ]=/=/g" | cut -d= -f1 | sort)
       if [[ ${ar_CNF[*]} == "${ar_cnf[*]}" ]]; then
          # get values supplied by "${CNF}", instead of "source ${CNF}"
-         _pattern="s/=[ ^ ]/=/g;s/['\";#$\(\)\|]//g;s/\(  \|\t\).*//g;s/\. [a0-z9].*/\./g"
+         _pattern="s/=[ ^ ]/=/g;s/['\";s/\(\)\|]//g;s/\(  \|\t\).*//g;s/\. [a0-z9].*/\./g"
          mapfile -t ar_VAR < <(_grep -Ev "^(#|*$|\s|\t)" "${CNF}" | _sed -e "${_pattern}" | sort | cut -d= -f2)
          for ARG in "${!ar_VAR[@]}"; do
             printf -v "${ar_CNF[ARG]}" "%s" "${ar_VAR[ARG]}"
