update.commit

diff --git a/libs/grab_library b/libs/grab_library
--- a/libs/grab_library
+++ b/libs/grab_library
@@ -5,7 +5,7 @@
 #   ngadimin@warnet-ersa.net
 # NOTE
 #   intended for use by other scripts, not to be executed directly.
-# shellcheck disable=SC2034 disable=SC2148
+# shellcheck disable=SC2034 disable=SC2148 disable=SC2154
 
 shopt -s expand_aliases
 alias _sort="LC_ALL=C sort --buffer-size=80% --parallel=3"
@@ -44,22 +44,21 @@ f_tmp() {   # remove temporary files, directories && arrays. generated during sc
    find /tmp -maxdepth 1 -type f -name "txt.*" -print0 | xargs -r0 mv -t .
 }
 f_klin() { printf "\n"; f_tmp; f_uset; }
-f_trap() { trap f_klin EXIT TERM; trap 'f_klin; printf "bye!\n"; exit 255' INT; }
+f_trap() { trap f_klin EXIT TERM; trap 'f_klin; exit 255' INT; }
 f_uset() { unset -v ar_{cat,CAT,cnf,CNF,db,dbc,DBC,dom,dmn,miss,reg,rpz,RPZ,sho,split,tmp,txt,url,VAR,zon} isDOWN index; }
 
 f_xcd() {   # exit code {6..21}
    for EC in $1; do
       local _xcd; _xcd=$(printf "${_err} $_foo: at line ${BASH_LINENO[0]}. exit code %s" "${EC}")
-      local _xce; _xce=$(printf "${_err} $_fuu: at line ${BASH_LINENO[0]}. exit code %s" "${EC}")
       case $EC in
           7) printf "\n%s\n%s\n" "${_xcd}" "required passwordless ssh to remote host: '$2'"; return 1;;
           8) printf "\n%s\n%s\n" "${_xcd}" "required '$2' but it's not installed"; return 1;;
           9) printf "\n%s\n%s\n" "${_xcd}" "'$2' required '$3' but it's not installed"; return 1;;
          10) printf "\n%s\n%s\n" "${_xcd}" "you must execute as non-root privileges"; return 1;;
-         11) _msj='urls. it should consist of 22 urls'
+         11) _msj="urls. it should consist of ${index[ar_url]} urls"
              printf -v _lmm "%s" "$(basename "$2"): $(wc -l < "$2")"
              printf "\n%s\n%s %s\n" "${_xcd}" "${_lmm}" "${_msj}"; return 1;;
-         12) _msg='lines. it should consist of 3 lines'
+         12) _msg="lines. it should consist of ${index[ar_reg]} lines"
              printf -v _lnn "%s" "$(basename "$2"): $(wc -l < "$2")"
              printf "\n%s\n%s %s\n" "${_xcd}" "${_lnn}" "${_msg}"; return 1;;
          13) _re0='[Exit Codes section] https://curl.se/docs/manpage.html'
@@ -67,14 +66,16 @@ f_xcd() {   # exit code {6..21}
              _unk='check out [grab_urls]. if url[s] are correct, please see'
              printf "${_err} %s:\n%s\n%s\n" "${_unk}" "${_re0}" "${_re1}"; exit 1;;
          14) printf "\n%s\n%s\n" "${_xcd}" "download failed from '$2'"; return 1;;
-         15) printf "\n%s\n%s\n" "${_xcd}" "category: must equal 6"; return 1;;
+         15) printf -v _ind "${_cyn}%s${_ncl}" "$(echo "${index[*]}" | grep "[\.,]")"
+             printf "%s\ninvalid index's values: %s\n" "${_xcd}" "${_ind}"
+             printf "${_hnt} use numeric in index's values%s\n"; return 1;;
          16) printf -v _lin "%s" "$(grep -En "^(HOST|#HOST)" "$CNF" | cut -d: -f1)"
              _ext=$(printf "${_err} ${CNF##*/} : at line ${_lin}. exit code: %s" "${EC}")
-             printf "\n%s\n%s : if this address is correct, maybe isDOWN\n" "${_ext}" "${HOST}"; return 1;;
-         17) printf "\n${_inf} misMATCH file(s): ${_cyn}%s${_ncl}\n%s\n" """$2""" "${_xcd}"; return 1;;
+             printf "%s\n%s : if this address is correct, maybe isDOWN\n" "${_ext}" "${HOST}"; return 1;;
+         17) printf "\n${_inf} misMATCH file(s): ${_cyn}%s${_ncl}\n%s\n" "$2" "${_xcd}"; return 1;;
          18) printf "\n%s: ${_cyn}%s${_ncl} doesn't exis\n" "${_xcd}" "$(basename "$2")"; return 1;;
-         19) printf "\n%s: file(s) must consist of,\n${_cyn}%s${_ncl}\n%s" "${_xcd}" """$2"""; return 1;;
-         20) printf "%s\nmissing file: %s\n" "${_xce}" "$(basename "$2")"; return 1;;
+         19) printf "\n%s: file(s) must consist of,\n${_cyn}%s${_ncl}\n%s" "${_xcd}" "$2"; return 1;;
+         20) printf "%s\nmissing file: ${_cyn}%s${_ncl}\n" "${_xcd}" "$2"; return 1;;
           *) _ukn="Unknown exit code [f_xcd $1], please check:"
              printf -v _knw "%s" "$_foo at line $(grep -n "f_xcd $1" "$_foo" | cut -d: -f1)"
              printf "\n${_err} %s\n%s\n" "${_ukn}" "${_knw}"; return 1;;
@@ -94,7 +95,7 @@ f_sm0() {   # display messages when getting options
    else
       printf "%6salso, ${_rnr} will be executed too\n" ""
    fi
-   printf "%4s) use Ctrl+C to quit\n" "*"
+   printf "%4s) use Ctrl+C to quit\n" "^C"
    printf "ENTER: ${_cyn}[1|2|3|4]${_ncl} or Ctrl+C to quit%s\n"
 }
 
@@ -104,13 +105,19 @@ f_sm1() {   # f_sm[1...4] = display messages when chosing option
    f_sm12 "st"
 }
 
+f_sm1() {   # f_sm[1...4] = display messages when chosing option
+   printf "\n${_red}[%s'st] TASK options chosen${_ncl}\n" "$RETVAL"
+   printf "${_cnt} 1) eliminating duplicate entries between CATEGORY%s\n"
+   f_sm12 "st"
+}
+
 f_sm2() { f_sm5 "nd"; f_sm12 "nd"; }
-f_sm3() { f_sm5 "th"; printf "%28s serial at zone-files [rpz.*]\n" "~incrementing"; f_sm12 "th"; }
+f_sm3() { f_sm5 "th"; printf "%30s serial at zone-files [rpz.*]\n" "2) incrementing"; f_sm12 "th"; }
 
 f_sm4() {
    f_sm5 "th"
-   printf "%28s serial zone-files [rpz.*]\n" "~incrementing"
-   printf "%28s latest [rpz.* and db.*] files to %s\n" "~syncronizing" "${HOST}"
+   printf "%30s serial zone-files [rpz.*]\n" "3) incrementing"
+   printf "%30s latest [rpz.* and db.*] files to %s\n" "4) syncronizing" "${HOST}"
    if [[ ${RNDC_RELOAD} =~ [nN][oO] ]]; then
       printf "%6s${_wrn} host %s will REBOOT due to low memory\n" "" "${HOST}"
       printf "%18s ${_shd} at HOST: %s to abort\n" "use" "${HOST}"
@@ -122,8 +129,8 @@ f_sm4() {
 
 f_sm5() {   # nested in f_sm[2...4]
    printf "\n${_red}[%s'%s] TASK options chosen${_ncl}\n" "$RETVAL" "$1"
-   printf "${_cnt} ~eliminating duplicate entries between CATEGORY%s\n"
-   printf "%25s all CATEGORIES to RPZ format [db.* files]\n" "~rewriting"
+   printf "${_cnt} 1) eliminating duplicate entries between CATEGORY%s\n"
+   printf "%27s all CATEGORIES to RPZ format [db.* files]\n" "2) rewriting"
 }
 
 f_sm6() {   # display FINISH messages
@@ -169,51 +176,6 @@ f_ssh() {   # nested in f_syn && f_cer
       _ssh root@"${HOST}" "hash $C >> /dev/null 2>&1" || f_xcd 9 "${HOST}" "$C"
    done
    f_ok
-}
-
-f_syn() {   # passwordless ssh for backUP oldDB and rsync newDB
-   if ping -w 1 "${HOST}" >> /dev/null 2>&1; then
-      # check existance of db-files and zone-files
-      ar_DBC=(db.adultaa db.adultab db.adultac db.adultad db.adultae db.adultaf db.adultag \
-         db.ipv4 db.malware db.publicite db.redirector db.trust+aa db.trust+ab)
-      ar_RPZ=(rpz.adultaa rpz.adultab rpz.adultac rpz.adultad rpz.adultae rpz.adultaf rpz.adultag \
-         rpz.ipv4 rpz.malware rpz.publicite rpz.redirector rpz.trust+aa rpz.trust+ab)
-
-      mapfile -t ar_dbc < <(f_fnd "db.*")
-      mapfile -t ar_rpz < <(f_fnd "rpz.*")
-      printf -v miss_DBC "%s" "$(echo "${ar_DBC[@]}" "${ar_dbc[@]}" | f_sed)"
-      printf -v miss_RPZ "%s" "$(echo "${ar_RPZ[@]}" "${ar_rpz[@]}" | f_sed)"
-
-      for DBC in ${ar_DBC[*]}; do [[ -e $DBC ]] || f_xcd 20 "$miss_DBC"; done
-      for RPZ in ${ar_RPZ[*]}; do [[ -e $RPZ ]] || f_xcd 20 "$miss_RPZ"; done
-      [[ ${ar_dbc[*]} == "${ar_DBC[*]}" ]] || f_xcd 19 "$miss_DBC"
-      [[ ${ar_rpz[*]} == "${ar_RPZ[*]}" ]] || f_xcd 19 "$miss_RPZ"
-      # end of check
-
-      local _ts; _ts=$(date "+%Y-%m-%d")
-      local _ID; _ID="/home/rpz-${_ts}.tar.gz"
-
-      f_ssh
-      printf "${_inf} archiving current RPZ-dBase, save in %s:%s\n" "${HOST}" "$_ID"
-      _ssh root@"${HOST}" "cd /etc/bind; tar -I pigz -cf $_ID zones-rpz"
-      printf "${_inf} find and remove old RPZ-dBase archive in %s:/home\n" "${HOST}"
-      _ssh root@"${HOST}" "find /home -regex '^.*\(tar.gz\)$' -mmin +1430 -print0 | xargs -0 -r rm"
-      printf "${_inf} syncronizing the latest RPZ-dBase to %s:%s\n" "${HOST}" "${ZONE_DIR}"
-      _rsync {rpz,db}.* root@"${HOST}":"${ZONE_DIR}"
-
-      if [[ ${RNDC_RELOAD} =~ [yY][eE][sS] ]]; then
-         # required sufficient RAM to execute "rndc reload"
-         printf "execute ${_rnr} at BIND9-server:%s\n" "${HOST}"
-         _ssh root@"${HOST}" "rndc reload"
-      else
-         # remote-host will reboot [after +@ minute] due to low memory
-         printf "${_inf} host: %s scheduled for reboot at ${_grn}%s${_ncl}\n" "${HOST}" "$_fkt"
-         _ssh root@"${HOST}" "shutdown -r 5 --no-wall >> /dev/null 2>&1"
-         printf "${_inf} use ${_shd} at host: %s to abort" "${HOST}"
-      fi
-   else
-      f_xcd 16
-   fi
 }
 
 f_crawl() {   # verify remote-urls isUP
@@ -285,24 +247,21 @@ f_ip4() {   # f_rpz && f_ip4 : both configurable in grab_config
 }
 
 f_cer() {   # used by grab_cereal.sh to copy zone-files with passwordless ssh & scp
-   if ping -w 1 "$HOST" >> /dev/null 2>&1; then
-      f_ssh
-      for a in $1; do
-         if scp root@"${HOST}":"${ZONE_DIR}"/"$a" "$_DIR" >> /dev/null 2>&1; then
-            printf "${_inf} successfully get %s from %s\n" "$a" "${HOST}"
-         else
-            local origin='https://raw.githubusercontent.com/ngadmini/Grabbing-Blacklist-for-Bind9-RPZ/master/zones-rpz/'
-            printf "${_err} %s not found in %s. %s\n" "$a" "${HOST}" "try to get from origin:"
-            printf "%s%s\n" "$origin" "$a"
-            curl -C - -fs "$origin""$a" >> "$a" || f_xcd 14 "$origin"
-            printf "${_inf} successfully get %s from origin\n" "$a"
-         fi
-      done
-      printf "${_inf} retry to running TASK again%s\n"
-      exec "$0"
-   else
-      f_xcd 16
-   fi
+   if ! ping -w 1 "$HOST" >> /dev/null 2>&1; then f_xcd 16; fi
+   f_ssh
+   for a in $1; do
+      if scp root@"${HOST}":"${ZONE_DIR}"/"$a" "$_DIR" >> /dev/null 2>&1; then
+         printf "${_inf} successfully get %s from %s\n" "$a" "${HOST}"
+      else
+         local origin='https://raw.githubusercontent.com/ngadmini/Grabbing-Blacklist-for-Bind9-RPZ/master/zones-rpz/'
+         printf "${_err} %s not found in %s. %s\n" "$a" "${HOST}" "try to get from origin:"
+         printf "%s%s\n" "$origin" "$a"
+         curl -C - -fs "$origin""$a" >> "$a" || f_xcd 14 "$origin"
+         printf "${_inf} successfully get %s from origin\n" "$a"
+      fi
+   done
+   printf "${_inf} retry to running TASK again%s\n"
+   exec "$0"
 }
 
 f_sed() { _sed "s/ /\n/g" | sort | uniq -u | tr "\n" " "; }
