v8.4-commit

diff --git a/libs/grab_library b/libs/grab_library
--- a/libs/grab_library
+++ b/libs/grab_library
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 # TAGS
 #   grab_library v8.4
+#   https://github.com/ngadmini
 # AUTHOR
 #   ngadimin@warnet-ersa.net
 # TL;DR
@@ -22,7 +23,7 @@ _ver=$(_grp -P "^#[[:space:]]+grab_" "${_foo}" | awk -F' ' '{print $NF}')
 _api="https://api.github.com/repos/ngadmini/Grabbing-Blacklist-for-Bind9-RPZ/releases/latest"
 _get=$(curl -s "${_api}" | grep download_url | awk -F/ '{print $8}')
 _ori="https://raw.githubusercontent.com/ngadmini/Grabbing-Blacklist-for-Bind9-RPZ/${_get}"
-_lct=$(date +%a\ %Y-%m-%d\ '%T %Z')
+_lct=$(date +%a\ %Y-%m-%d\ %T\ %Z)
 
 # colorizing
 _cyn='\e[96m'; _grn='\e[92m'; _ncl='\e[0m'; _red='\e[91m'; _ylw='\e[93m'
@@ -56,7 +57,7 @@ f_set() {
 }
 
 f_cln() { printf "\n"; f_tmp; f_set; }
-f_trp() { trap f_cln EXIT TERM; trap 'f_cln; exit 130' INT; }
+f_trp() { trap f_cln EXIT TERM INT; }
 
 f_xcd() {   # exit code {244..255}
    for EC in $1; do
@@ -159,7 +160,7 @@ f_tim() { # time elapsed in Minute:Second.milisecond
 f_up() { printf "${_GRN}\n" "isUP"; }
 f_ok() { printf "${_GRN}\n" "isOK"; }
 f_do() { printf "${_GRN}\n" "DONE"; }
-f_no() { printf "\n${_err} missing file(s):\n${_CYN}\n" "$1"; }
+f_no() { printf "\n${_err} missing file(s): ${_CYN}\n" "$1"; }
 
 # grabbing raw-domains
 f_add() { curl --retry 5 --retry-all-errors -f -s "$1" || f_xcd 251 "$1"; }
@@ -296,9 +297,9 @@ f_cer() {   # used by grab_cereal.sh [grabbing zone-files if notFOUND]
    f_ssh
    for a in $1; do
       if scp root@"${HOST}":"${ZONE_DIR}"/"${a}" "${_DIR}" >> /dev/null 2>&1; then
-         printf "${_inf} fetch files from %s:\n${_CYN}" "${HOST}" "${a}"
+         printf "${_inf} fetch files from %s: ${_CYN}\n" "${HOST}" "${a}"
       else
-         printf "${_err} notFOUND in %s:\n${_CYN}\n" "${HOST}" "${a}"
+         printf "\n${_err} notFOUND in %s:\n${_CYN}\n" "${HOST}" "${a}"
          f_ori "zones-rpz/${a}" "${a}"
       fi
    done
@@ -318,12 +319,12 @@ f_ori() {
    fi
 }
 
-f_mis() { printf "\n${_err} missing file(s):\n${_CYN}" "$1"; f_xcd 255 "$2"; }
+f_mis() { printf "\n${_err} mismatch file(s): ${_CYN}" "$1"; f_xcd 255 "$2"; }
 f_sed() { _sed "s/ /\n/g" | _srt | uniq -u | tr "\n" " " | _sed "s/ $//g"; }
 f_fnd() { find . -maxdepth 1 -type f -name "$1" | _sed "s/\.\///" | _srt; }
 f_frm() { find . -maxdepth 1 -type f -name "$1" -print0 | xargs -r0 rm; }
 f_cat() { find . -maxdepth 1 -type d | _sed "1d;s/\.\///" | _srt; }
-f_sta() { if [[ $(stat -L -c "%a" "$2") != "$1" ]]; then chmod "$1" "$2"; fi; }
+f_sta() { if [[ $(stat -c "%a" "$2") != "$1" ]]; then chmod "$1" "$2"; fi; }
 f_stt() { printf "\n${_RED}\nstarting ${0##*/} ${_ver} at ${_CYN}\n" "$1" "${_lct}"; f_ver; }
 
 f_dft() {   # define default values in grab_config
